title: Raymond'Log
name: "Raymond's Tech Blog"
author: Raymond Lau
twitter_username: raymond-log
baseurl: "/raymond-log"
description: Document my learning notes.
profile_url: "http://HappyRaymond.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3
